// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import graphql "github.com/veritone/graphql"
import mock "github.com/stretchr/testify/mock"

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// Run provides a mock function with given fields: ctx, req, resp
func (_m *Client) Run(ctx context.Context, req *graphql.Request, resp interface{}) error {
	ret := _m.Called(ctx, req, resp)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *graphql.Request, interface{}) error); ok {
		r0 = rf(ctx, req, resp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetLogger provides a mock function with given fields: _a0
func (_m *Client) SetLogger(_a0 func(string)) {
	_m.Called(_a0)
}
